### ISSUE TITLE
voluputous update breaking change

### ISSUE THREAD

**Issue by lolorc** [elric91/homeassistant_zigate#10]
Hi,

I'm using HA dev branch, upcoming breaking change has been merged in dev few days ago:
see https://github.com/home-assistant/home-assistant/pull/12463

**Comment by elric91** [comment]
thanks for noticing, should not be too complex to make right

**Comment by lolorc** [comment]
sure, I've downgraded to 0.63.3 cause I don't have time to provide a PR for this.
looking at https://twitter.com/home_assistant/status/961677072614780928
it looks like next HASS release will be there by the end of February ;-)

**Comment by ISO-B** [comment]
Pushed commit that should fix this.

**Comment by lolorc** [comment]
thanks, just tried it, looks ok, no error so far
