### ISSUE TITLE
Momentary switch value per switch

### ISSUE THREAD

**Issue by max5962** [elric91/homeassistant_zigate#12]
Hello,

Is it possible to tweak the value of the momentary switch (actually 15 s in the const.py) per switch ?

Thanks :)

**Comment by max5962** [comment]
one workaround is to condition "for" : 

- alias: extinction_auto_couloir
  trigger:
    platform: state
    entity_id: switch.sensor1
    from: 'on'
    to: 'off'
    for:
      seconds: 30

**Comment by ISO-B** [comment]
There is now new configuration parameter for switch, autotoggle_delay.
