### ISSUE TITLE
Address in quote in the wiki & Aqara push button example

### ISSUE THREAD

**Issue by RiRomain** [elric91/homeassistant_zigate#21]
It seems it's not possible to contribute to the wiki in github, so I'm making a change request here.

- As a follow up from https://github.com/elric91/homeassistant_zigate/issues/19 , all address should be in between double-quote to avoid problem with numerical only device address.
- And a new example for the aqara Push button:
## Aqara push button (only single click supported)
    switch:
      - platform: zigate
        name: 'Switch01'
        address: "f5c901"
        autotoggle_delay: 2
        default_state: 'state'
        type: 'toggle'

**Comment by elric91** [comment]
Thanks !
Added to the wiki
