### ISSUE TITLE
Unable to run check_config with sensor.zigate

### ISSUE THREAD

**Issue by ruimarinho** [elric91/homeassistant_zigate#24]
My config loads and runs fine on HASS but testing config has been broken since the installation of zigate as a custom component.

If I run:

```
docker run --rm -v $(pwd):/config -ti homeassistant/home-assistant:0.67.1 python -m homeassistant -c /config --script check_config
```

The output is:

```
Testing configuration at /config
Failed config
  General Errors:
    - Platform not found: sensor.zigate
    - Platform not found: sensor.zigate
    - Platform not found: sensor.zigate
```

The custom sensor file is available at `custom_components/sensor/zigate.py`. Any ideas why `check_config` isn't picking up the custom version?

**Comment by ruimarinho** [comment]
Thanks @elric91 - to be clear, the component itself works (0.67.1 works fine for me as well), it's just the `check_config` command that isn't loading the component correctly. I have other custom components working fine, so my guess is that it's something related to the way to the component is setup.

See https://travis-ci.org/ruimarinho/home-assistant-config/builds/369629737 for the test build using 0.13.post2.

**Comment by elric91** [comment]
Strange ..
I tested a fresh build (0.67.1 / 0.13.post2)

hass --config ~/.homeassistant/ --script check_config
Testing configuration at /home/zzz/.homeassistant/

no complaints from the script ... don't know
just a guess : are the authorizations on your custom_component/sensor/zigate.py OK from the perspective of the user who launches the test in travis ?

**Comment by acesyde** [comment]
Hi,

Same problem here with HASS 0.71.0 and the last version of component

Build : https://travis-ci.org/acesyde/Home-Assistant/builds/394987048
Repo : https://github.com/acesyde/Home-Assistant

**Comment by mvdkleijn** [comment]
Latest version of the component and latest version of HASS... No issues here.

**Comment by ISO-B** [comment]
Tested with HASS 0.82.1 without issues. If issues appear again reopen or create new issue.
