### ISSUE TITLE
Compatibility with ZiGate 3.0f

### ISSUE THREAD

**Issue by ruimarinho** [elric91/homeassistant_zigate#31]
Hi @elric91,

Is this component compatible with the newest 3.0f release of ZiGate?

Thank you,

**Comment by ISO-B** [comment]
I think that 3.0e is newest released firmware version of ZiGate. I can find 3.0f source files but there is no change log so can't say for sure, but I don't see why it wouldn't work. You can always downgrade your firmware if it doesn't work.

**Comment by ruimarinho** [comment]
Looks like a binary hasn't been released yet. I'll flag that.

There is a more recent python library called [zigate](https://pypi.org/project/zigate/) which adds support for 3.0e and 3.0f. As a side note, maybe we should consolidate efforts and switch to that one instead of pyzigate?

**Comment by ISO-B** [comment]
I need to take a look how it would work with plugin. We need some signals from library.
