### ISSUE TITLE
Restore state seems not to be working since 0.84

### ISSUE THREAD

**Issue by Peekayy** [elric91/homeassistant_zigate#32]
Since I upgraded to 0.84, after restarting homeassistant server, all values from zigate sensors are empty. I believe this is not intended. Or did I miss some configuration ?

**Comment by elric91** [comment]
Indeed. I just modified it to prevent it from being blocked at start in 0.84 then noticed restore was not properly working (and did not managed to fix it in the few hours I had). Will have a deeper look this WE.

**Comment by Peekayy** [comment]
It's alright ! I'd love to help but my knowledge of the python ecosystem is non existent!
Anyway, thanks for your work.

**Comment by elric91** [comment]
Working again with last commit
