### ISSUE TITLE
Feedback: init service tested

### ISSUE THREAD

**Issue by mvdkleijn** [elric91/homeassistant_zigate#9]
Hi there,

I don't have a Windows system at home and was happy to see the new init service in master... So I took the liberty to test it.

Seems to work flawlessly on my raspberry pi 3b with hassio Docker version 0631

I at least managed to get my xiaomi temperature sensor up and running with it.

Thanks! :smile:

**Comment by elric91** [comment]
Thanks for the test and confirmation !
(I'll publish a new release later on to include it)
